INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Valera', 'Ge AWS Certified', CURRENT_DATE(), FALSE);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'Valera', 'Ge         dwdwd', CURRENT_DATE(), FALSE);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Valera', 'Ge AWS Cdwdwdied', CURRENT_DATE(), FALSE);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Valera', ' Certifdwdwdwied', CURRENT_DATE(), FALSE);
